beginning of hardware_test implementation

diff --git a/src/jenkins_setup/templates/execute_shell.yaml b/src/jenkins_setup/templates/execute_shell.yaml
--- a/src/jenkins_setup/templates/execute_shell.yaml
+++ b/src/jenkins_setup/templates/execute_shell.yaml
@@ -572,8 +572,96 @@ echo "***********LEAVE CHROOT************"
 #####################
 ### hardware_test ###
 #####################
-'hardware_test': '#!/bin/bash -e
+'hardware_test': '#!/bin/bash 
 
-    #TODO
+if [ -z "$ROS_DISTRO" ]; then
 
+echo "set ROS_DISTRO"
+
+ROS_DISTRO=$ros_distro
+
+fi
+
+if [ -z "$ros_distro" ]; then
+
+echo "set ros_distro"
+
+ros_distro=$ROS_DISTRO
+
+fi
+
+new_basetgz=${ubuntu_distro}__${arch}__${ROS_DISTRO}
+
+basetgz=@(USERNAME)__${new_basetgz}__${repository}
+
+
+sudo rm -rf $WORKSPACE/*
+
+if [ -d $WORKSPACE/../aux ]; then
+
+sudo rm -rf $WORKSPACE/../aux
+
+fi
+
+mkdir $WORKSPACE/../aux
+
+
+echo "Copying "$basetgz" from @(STORAGE)/in_use_on__@(SERVERNAME)"
+
+scp @(STORAGE)/in_use_on__@(SERVERNAME)/$basetgz $WORKSPACE/../aux/${basetgz}
+
+scp -r jenkins@@(SERVERNAME):.ssh $WORKSPACE/
+
+scp -r jenkins@@(SERVERNAME):@(CONFIG_FOLDER)/jenkins_setup $WORKSPACE/
+
+ls -lah $WORKSPACE
+
+
+cat &gt; $WORKSPACE/env_vars.sh &lt;&lt;DELIM
+
+JOBNAME=$JOB_NAME
+
+ROSDISTRO=$ROS_DISTRO
+
+REPOSITORY=$repository
+
+UBUNTUDISTRO=$ubuntu_distro
+
+ARCH=$arch
+
+PIPELINE_REPOS_OWNER=@(PIPELINEREPOSOWNER)
+
+JENKINS_MASTER=@(SERVERNAME)
+
+JENKINS_USER=@(USERNAME)
+
+JOBTYPE=@(JOB_TYPE_NAME)
+
+export ROS_TEST_RESULTS_DIR=/tmp/test_repositories/src_repository/test_results
+
+export BUILD_ID=$BUILD_ID
+
+DELIM
+
+
+ls -lah $WORKSPACE
+
+$WORKSPACE/jenkins_setup/scripts/graphicTest/host/prepareForChroot.bash $WORKSPACE
+
+if [ $? != 0 ]; then
+
+echo "Error: Preparation failed"
+
+exit 1
+
+fi
+
+
+echo "***********ENTER CHROOT************"
+
+
+sudo pbuilder execute --basetgz $WORKSPACE/../aux/${basetgz} --bindmounts "$WORKSPACE /tmp/.X11-unix /tmp/nvidia" -- $WORKSPACE/jenkins_setup/scripts/pbuilder_env.sh $WORKSPACE
+
+echo "***********LEAVE CHROOT************"
 '
+
